# Generated by Django 6.0.1 on 2026-02-15 08:34

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 15, 8, 34, 45, 811045, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 15, 8, 34, 45, 811055, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "memory",
                    models.TextField(
                        blank=True, default="", max_length=5000, null=True
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.character"
                    ),
                ),
                (
                    "me",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userprofile",
                    ),
                ),
            ],
        ),
    ]
