# Generated by Django 6.0.1 on 2026-03-07 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_character_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 7, 9, 38, 49, 810387, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 7, 9, 38, 49, 810397, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(max_length=10000),
        ),
    ]
