# Generated by Django 6.0.1 on 2026-03-08 02:56

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_character_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("order_by", models.IntegerField(default=0)),
                ("prompt", models.TextField(max_length=100000)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 2, 56, 35, 594290, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 2, 56, 35, 594300, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
