# Generated by Django 6.0.1 on 2026-03-08 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_systemprompt_alter_character_create_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemprompt",
            old_name="order_by",
            new_name="order_number",
        ),
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 4, 0, 21, 813669, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 4, 0, 21, 813680, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
