# Generated by Django 6.0.1 on 2026-03-08 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_rename_order_by_systemprompt_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 4, 43, 13, 401545, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 4, 43, 13, 401555, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
