# Generated by Django 6.0.1 on 2026-03-08 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_alter_character_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 4, 44, 11, 748089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 8, 4, 44, 11, 748099, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
